### PR TITLE
Update apt-repository.md

### PR DESCRIPTION
**Pull request by queenkjuul**
I accidentally opened the issue on the wrong project lol my bad (in my defense it was very late and I had consumed a few adult beverages)

makedeb/makedeb-docs#30

i think this should fix it for you but I mostly just wanted yall to be aware of the problem. I am not sure how to test this to be 100% sure but when I installed the repo I used the same proget URL from a few lines above, so that's what I copied here, so it makes sense in my mind. 

anyway cheers

### CODE REVIEW

**Comment by hwittenborn** [comment]
Can you merge in the changes I just added to `master`? It should automatically deploy to Netlify after you do that so I can preview your changes.

**Comment by queenkjuul** [comment]
should be good

**Comment by hwittenborn** [comment]
It looks like you still need to merge in the changes for the Netlify config - looking at your repo it looks like it's still 3 commits behind.

**Comment by hwittenborn** [comment]
I can just do it myself if you'd like to, I just need to know if you're fine with that.

**Comment by queenkjuul** [comment]
hmm I went to my repo and hit "fetch upstream" (in github)

you are welcome to do whatever you like though

**Comment by queenkjuul** [comment]
oh lol i gotcha. sorry I use gitlab at work and am pretty new to this cross-fork pull request workflow

**Comment by hwittenborn** [comment]
All good :)

Preview looks fine too, I'll go ahead and get this merged then

**Pull request merged**
